# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ipno-apn_on_rails"
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["markbates", "Rebecca Nesson", "Jonathan Bell", "Sebastian Raducci"]
  s.date = "2011-12-14"
  s.description = "APN on Rails is a Ruby on Rails gem that allows you to\neasily add Apple Push Notification (iPhone) support to your Rails application using MongoMapper.\n"
  s.email = "raducci@datamind.biz"
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "README.textile"
  ]
  s.files = [
    ".rspec",
    ".specification",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README",
    "README.textile",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "generators/apn_migrations_generator.rb",
    "generators/templates/apn_migrations/001_create_apn_devices.rb",
    "generators/templates/apn_migrations/002_create_apn_notifications.rb",
    "generators/templates/apn_migrations/003_alter_apn_devices.rb",
    "generators/templates/apn_migrations/004_create_apn_apps.rb",
    "generators/templates/apn_migrations/005_create_groups.rb",
    "generators/templates/apn_migrations/006_alter_apn_groups.rb",
    "generators/templates/apn_migrations/007_create_device_groups.rb",
    "generators/templates/apn_migrations/008_create_apn_group_notifications.rb",
    "generators/templates/apn_migrations/009_create_pull_notifications.rb",
    "generators/templates/apn_migrations/010_alter_apn_notifications.rb",
    "generators/templates/apn_migrations/011_make_device_token_index_nonunique.rb",
    "generators/templates/apn_migrations/012_add_launch_notification_to_apn_pull_notifications.rb",
    "lib/apn_on_rails.rb",
    "lib/apn_on_rails/apn_on_rails.rb",
    "lib/apn_on_rails/app/models/apn/app.rb",
    "lib/apn_on_rails/app/models/apn/device.rb",
    "lib/apn_on_rails/app/models/apn/device_grouping.rb",
    "lib/apn_on_rails/app/models/apn/group.rb",
    "lib/apn_on_rails/app/models/apn/group_notification.rb",
    "lib/apn_on_rails/app/models/apn/notification.rb",
    "lib/apn_on_rails/app/models/apn/pull_notification.rb",
    "lib/apn_on_rails/libs/connection.rb",
    "lib/apn_on_rails/libs/feedback.rb",
    "lib/apn_on_rails/tasks/apn.rake",
    "lib/apn_on_rails/tasks/db.rake",
    "lib/apn_on_rails_tasks.rb",
    "spec/apn_on_rails/app/models/apn/app_spec.rb",
    "spec/apn_on_rails/app/models/apn/device_spec.rb",
    "spec/apn_on_rails/app/models/apn/group_notification_spec.rb",
    "spec/apn_on_rails/app/models/apn/notification_spec.rb",
    "spec/apn_on_rails/app/models/apn/pull_notification_spec.rb",
    "spec/apn_on_rails/libs/connection_spec.rb",
    "spec/apn_on_rails/libs/feedback_spec.rb",
    "spec/extensions/string.rb",
    "spec/factories/app_factory.rb",
    "spec/factories/device_factory.rb",
    "spec/factories/group_factory.rb",
    "spec/factories/group_notification_factory.rb",
    "spec/factories/notification_factory.rb",
    "spec/factories/pull_notification_factory.rb",
    "spec/fixtures/hexa.bin",
    "spec/fixtures/message_for_sending.bin",
    "spec/mongo_mapper/setup_mongo_mapper.rb",
    "spec/rails_root/config/apple_push_notification_development.pem",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/ipno/apn_on_rails"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.12"
  s.summary = "Apple Push Notifications on Rails for MongoMapper"
  s.test_files = [
    "spec/apn_on_rails/app/models/apn/app_spec.rb",
    "spec/apn_on_rails/app/models/apn/device_spec.rb",
    "spec/apn_on_rails/app/models/apn/group_notification_spec.rb",
    "spec/apn_on_rails/app/models/apn/notification_spec.rb",
    "spec/apn_on_rails/app/models/apn/pull_notification_spec.rb",
    "spec/apn_on_rails/libs/connection_spec.rb",
    "spec/apn_on_rails/libs/feedback_spec.rb",
    "spec/extensions/string.rb",
    "spec/factories/app_factory.rb",
    "spec/factories/device_factory.rb",
    "spec/factories/group_factory.rb",
    "spec/factories/group_notification_factory.rb",
    "spec/factories/notification_factory.rb",
    "spec/factories/pull_notification_factory.rb",
    "spec/mongo_mapper/setup_mongo_mapper.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<configatron>, [">= 0"])
      s.add_development_dependency(%q<autotest>, [">= 0"])
      s.add_development_dependency(%q<mongo>, ["= 1.3.0"])
      s.add_development_dependency(%q<bson>, ["= 1.3.0"])
      s.add_development_dependency(%q<bson_ext>, ["= 1.3.0"])
      s.add_development_dependency(%q<mongo_mapper>, ["= 0.9.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<actionpack>, ["~> 3.0.6"])
    else
      s.add_dependency(%q<configatron>, [">= 0"])
      s.add_dependency(%q<autotest>, [">= 0"])
      s.add_dependency(%q<mongo>, ["= 1.3.0"])
      s.add_dependency(%q<bson>, ["= 1.3.0"])
      s.add_dependency(%q<bson_ext>, ["= 1.3.0"])
      s.add_dependency(%q<mongo_mapper>, ["= 0.9.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<actionpack>, ["~> 3.0.6"])
    end
  else
    s.add_dependency(%q<configatron>, [">= 0"])
    s.add_dependency(%q<autotest>, [">= 0"])
    s.add_dependency(%q<mongo>, ["= 1.3.0"])
    s.add_dependency(%q<bson>, ["= 1.3.0"])
    s.add_dependency(%q<bson_ext>, ["= 1.3.0"])
    s.add_dependency(%q<mongo_mapper>, ["= 0.9.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<actionpack>, ["~> 3.0.6"])
  end
end

